definitions:
  domain.Cart:
    properties:
      customer_id:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/domain.CartItem'
        type: array
      total_items:
        type: integer
      total_price:
        type: number
    type: object
  domain.CartItem:
    properties:
      product_id:
        type: string
      product_name:
        type: string
      product_price:
        type: number
      quantity:
        type: integer
      subtotal:
        type: number
    type: object
  domain.CartItemRequest:
    properties:
      product_id:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/cart_service/carts/{id}:
    delete:
      consumes:
      - application/json
      description: Clear all items from the customer's cart
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Clear cart
      tags:
      - Cart
    get:
      consumes:
      - application/json
      description: Retrieve the cart for a specific customer
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Cart'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get cart by customer ID
      tags:
      - Cart
    post:
      consumes:
      - application/json
      description: Add a product to the customer's cart
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      - description: Cart Item Request
        in: body
        name: cartItem
        required: true
        schema:
          $ref: '#/definitions/domain.CartItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Cart'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Add item to cart
      tags:
      - Cart
    put:
      consumes:
      - application/json
      description: Update an existing item in customer's cart
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      - description: Cart Item Request
        in: body
        name: cartItem
        required: true
        schema:
          $ref: '#/definitions/domain.CartItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Cart'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update cart item
      tags:
      - Cart
  /api/cart_service/carts/{id}/item/{product_id}:
    delete:
      consumes:
      - application/json
      description: Remove a product from the customer's cart
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Cart'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Remove item from cart
      tags:
      - Cart
swagger: "2.0"
