definitions:
  domain.Customer:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  domain.CustomerRequest:
    properties:
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/customer_service/customers:
    get:
      consumes:
      - application/json
      description: Retrieve all customers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Customer'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get all customers
      tags:
      - Customers
    post:
      consumes:
      - application/json
      description: Create a new customer with the provided details
      parameters:
      - description: Customer details
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/domain.CustomerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Customer'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new customer
      tags:
      - Customers
  /api/customer_service/customers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a customer by their ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Customer'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete a customer
      tags:
      - Customers
    get:
      consumes:
      - application/json
      description: Retrieve a customer by their ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Customer'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get customer by ID
      tags:
      - Customers
    put:
      consumes:
      - application/json
      description: Update an existing customer with the provided details
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      - description: Customer details
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/domain.CustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Customer'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update an existing customer
      tags:
      - Customers
swagger: "2.0"
